### ISSUE TITLE
Sugestão de Alteração na adição de novas transações

### ISSUE THREAD

**Issue by codingwithvm** [artur-debv/dev-finance#2]
Ao adicionar uma nova transação, está indo para a última linha da tabela. As transações mais recentes devem ficar no topo da tabela, acho que faz mais sentido :D.

**ALTERAÇÃO**
Mude esse trecho do código :
`DOM.transactionsContainer.appendChild(tr); // Adiciona a linha da tabela ao container de transações`

para:
`DOM.transactionsContainer.preprend(tr); // Adiciona a linha da tabela ao container de transações`

**Comment by artur-debv** [comment]
olá boa Noite, dei uma olhada, irie modificar, obrigado pelo feedback

**Comment by artur-debv** [comment]
Já dei uma modificado nesse trecho de código, qualquer outra solução, pode trazer, vamos conversando
